import { ReactNode } from "react";

export const metadata = {
  title: "Anonymity",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Favicon link here */}
        <link rel="icon" href="/anonymityLogo.ico" />
      </head>
      <body>{children}</body>
    </html>
  );
}
